paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: assets
  uploads: assets/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    _enabled_editors:
      - visual
    path: content
    description: Pages description
    output: true
    # filter: 
    #   exclude:
    #     - .html
    parse_branch_index: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      page:
        path: .cloudcannon/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        new_preview_url: /
  articles:
    _enabled_editors:
      - visual
    path: articles
    description: Articles description
    output: true
    disable_add: false
    disable_add_folder: false
    disable_add_file_actions: false
    schemas:
      page:
        path: .cloudcannon/schemas/article.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        new_preview_url: /
  # detail_pages:
  #   _enabled_editors:
  #     - visual
  # faculty:
  # guide_pages:
  home_page:
    _enabled_editors:
      - visual
  # news:
  # places_and_spaces:
  # profiles:
  #   _enabled_editors:
  #     - data
  #   path: content/profiles
  #   description: Profile description
  #   output: false
  #   icon: id-card
  #   disable_add: false
  #   disable_add_folder: false
  #   disable_file_actions: false
  #   schemas:
  #     profile:
  #       path: .cloudcannon/schemas/profile.md
  #       icon: person
  #       name: Student
  # programs:
  # staff:
  # students:
  # default_content:
  # site_config:
  #   path: data/site_config.yml
  #   description: Site configuration
  #   output: false
  #   icon: data_usage
  #   disable_add: true
  #   disable_add_folder: true
  #   disable_file_actions: false
# collection_groups:
#   - heading: Site Pages
#     collections:
#       - articles
#       - detail_pages
#       - guide_pages
#       - home_page
#       - news
#   - heading: People
#     collections:
#       - faculty
#       - staff
#       - students
#   - heading: Places and Spaces
#     collections:
#       - places_and_spaces
#   - heading: Profiles
#     collections:
#       - profiles
#   - heading: Data
#     collections:
#       - data
#   - heading: Default Content
#     collections:
#       - default_content
#   - heading: Site Config
#     collections:
#       - site_config
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  # page_collection_items:
  #   type: array
  #   options:
  #     structures: _structures.page_collection_item
  publish_date:
    type: date
    instance_value: NOW
  type:
    type: auto
    hidden: true
    cascade: true
# _structures:
#   page_collection_item:
#     values:
#       - label: Page
#         _inputs:
#           page:
#             type: select
#             values: collections.pages
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    bulletedlist: true
    code: true
    copyformatting: true
    embed: true
    format: p h2 h3 h4 h5 h6
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    snippet: true
    strike: true
    styles: /assets/scss/custom/_content.scss
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
data_config: true
timezone: US/Eastern
_snippets:
  figure:
    template: hugo_shortcode_named_args
    inline: false
    picker_preview:
      gallery:
        image: .cloudcannon/shortcode_previews/figure.webp
        icon: image
      text: Figure
      icon: image
      subtext: An image with an optional caption below
    preview:
      view: gallery
      gallery:
        image:
          - key: image_source
      text:
        - key: image_alt
        - Image has no alternative text
      icon: image
      metadata:
        - icon: folder
          text:
            - key: image_source
        - icon: closed_caption
          text:
            - key: caption
    definitions:
      shortcode_name: figure
      named_args:
        - editor_key: image_source
          type: string
          optional: false
        - editor_key: image_alt
          type: string
          optional: false
        - editor_key: caption
          type: string
          optional: true
    _inputs:
      image_source:
        type: image
        cascade: true
      caption:
        type: textarea
        cascade: true
  blockquote:
    template: hugo_shortcode_named_args
    inline: false
    picker_preview:
      gallery:
        image: .cloudcannon/shortcode_previews/blockquote.webp
        icon: format_quote
      text: Blockquote
      icon: format_quote
    preview:
      text:
        - key: quote
        - Quote
      icon: format_quote
      metadata:
        - text:
            - key: author
          icon: account_box
    definitions:
      shortcode_name: blockquote
      named_args:
        - editor_key: quote
          type: string
          optional: false
        - editor_key: author
          type: string
          optional: false
    _inputs:
      quote:
        type: textarea
        cascade: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_figure