baseURL: 'https://example.org/'
languageCode: en-us
title: Web Community
designSystemMenu: design_system
cmsMenu: cms
staticDir: assets
module:
  imports:
  - path: github.com/wvuweb/wvu-ds-v3-hugo
  - path: components.local
  - path: github.com/cloudcannon/bookshop/hugo/v3
  - path: github.com/wvuweb/wvu-ds-v3-bookshop-components
    mounts:
    - source: component-library
      target: layouts/partials/bookshop/
    - source: component-library
      target: assets/bookshop/
  replacements:
    - components.local -> ../component-library
    # - 'github.com/wvuweb/wvu-ds-v3-hugo -> ../../wvu-ds-v3-hugo'
    # - 'github.com/wvuweb/wvu-ds-v3-bookshop-components -> ../../wvu-ds-v3-bookshop-components'
markup:
  goldmark:
    renderer:
      unsafe: true
menus:
  main:
  - name: Request a Site
    pageRef: /request-a-site
    weight: 20
  - name: Content Strategy
    pageRef: /content-strategy
    weight: 30
  - name: Content Managers
    pageRef: /content-managers
    weight: 40
  - name: Designers and Developers
    pageRef: /designers-and-developers
    weight: 50
  - name: Design System
    pageRef: /design-system
    weight: 60
  - name: CMS
    pageRef: /cms
    weight: 70
  - name: FAQs
    pageRef: /faqs
    weight: 80