# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  elements:
    background_image:
      # src: "https://designsystemv2demo.sandbox.wvu.edu/files/e4742958-d585-48b8-ade6-7f45ab929897/1780x1780"
      alt:
    super_heading:
      icon: "location-dot"
      label: "Label"
      text: "Super Heading"
    heading: "Hello, world!"
    subheading: "Subheading"
    lead: "Lead text."
    copy: "Copy."
  config:
    is_main: false
    id: "hero"
    aria_labelled_by: "hero"
  layout:
    is_fluid: false
    align: "start"
    padding_y: "py-8"
  styles:
    vibe: 
    section:
      background_color: "bg-dark"
      blend_mode: 
      text_color: "text-white"
    background_layers:
      photo:
        blend_mode:
        filter:
        value:
      pattern:
        option: "wvu-bg-topo-dark"
        color: "bg-dark"
        blend_mode:
        opacity:
      texture:
        color: "wvu-bg-texture"
        blend_mode:
    super_heading:
      label:
        font: "wvu-shout"
        case:
        color: "text-wvu-gold"
      text:
        font: "helvetica-neue-light"
        color: 
        tracking: 
    heading:
      font: "wvu-shout"
      color: 
      case: "text-uppercase"
      decoration: "wvu-bar"
    subheading:
      font: "helvetica-neue-bold"
      size: "h1"
      weight: 
    lead:
      font: "helvetica-neue-light"
      size: "fs-3"
    copy:
      font:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
