# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero w/Search"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
    image:
    alt:
  heading: Lorem Ipsum Dolor Sit Amet
  lead: Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  body:
  ctas:
    - text: Call to Action
      url: /
  config:
    is_main: false
    id: hero
    aria_labelledby: hero-1-label
  layout:
    justify_content: left
    padding_y: py-8
    ctas: buttons
    show_number: false
  styles:
    background_c: bg-transparent
    background_image_blend_mode: normal
    background_pattern:
    heading_size: display-2
    heading_c: text-dark
    heading_extras:
    text_container:
    text_c: text-white
    thick_border: false
    button_size:
    button_color:
    button_color_first:
    list_style_type:
    list_color:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: