# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Page Collection"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"
  heading:
  lead:
  page_collection_items:
    - page:
      title_override:
      tease_override:
      cta_text_override:
      accent_c:
  postscript:
    text:
    ctas:
  layout:
    margin_y:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  page_collection_items:
    type: array
  page:
    structures: _structures.page_collection_page
_structures:
  page_collection_page:
    values:
      - label: Page
        value:
          page:
        _inputs:
          page:
            type: select
            values: collections.pages