# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Page Collection"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"
  page_collection_items:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  page_collection_items:
    type: array
    options:
      structures: _structures.page_collection_item
_structures:
  page_collection_item:
    values:
      - label: Page
        _inputs:
          page:
            type: select
            values: collections.pages